name:    a003-authenticated-map-merkle-trees
version: "0.0.0"
license: BSD3

dependencies:
- base
- bytestring
- cereal
- containers
- hspec
- monads-tf
- random
- SHA2

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fwarn-tabs
  - -O2

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - a003-authenticated-map-merkle-trees
    - hspec
