name:    a001-the-chain-in-blockchain
version: "0.0.0"
license: BSD3

dependencies:
- base
- bytestring
- classy-prelude
- containers >= 0.5.10.2
- cryptohash
- hspec
- text

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fwarn-tabs
  - -O2

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - a001-the-chain-in-blockchain
    - hspec
